### ISSUE TITLE
'flutter_line_sdk/flutter_line_sdk-Swift.h' file not found

### ISSUE THREAD

**Issue by shinzenkoru** [line/flutter_line_sdk#5] opened 2019-10-13 14:54 UTC
## What did you do?

Adding flutter_line_sdk to the Flutter project.

## What did you expect?

Running the project without any errors.

## What happened actually?

Try running both `flutter run` and  running on Xcode, the error stated that  `'flutter_line_sdk/flutter_line_sdk-Swift.h' file not found`

## Your environment?

flutter_line_sdk 1.0.3
Flutter 1.10.7
Xcode 11.0
macOS 10.15

**Comment by onevcat** [comment] 2019-10-15 02:11
Hi, @shinzenkoru 

Can you make sure that you have followed the [iOS integration guide](https://github.com/line/flutter_line_sdk#set-up-line-sdk), especially added the `use_frameworks!` to the Podfile?

And it would be also helpful if you can check and paste your CocoaPods version (`pod --version`) and the result of `flutter doctor` so we can know more about your environment. Thanks!

**Comment by onevcat** [comment] 2019-10-15 02:12
Especially there is [a known issue](https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices) that you may need CocoaPods 1.7.5 to install a plugin correctly. Any 1.8.x version would fail the check.

**Comment by onevcat** [comment] 2019-10-25 01:40
Since there is no further information and we cannot reproduce it, I am closing it for now.

Please feel free to reopen it or submit another issue if you have more informatiion.

**Closed by onevcat** 2019-10-25 01:40 UTC
